// 🔒 LOCKED [CLAUDE-INTEGRATION] — 2026-06-11
// ⛔ NEVER change the BEGIN/END managed-block markers without a migration
//    path. Users will have these markers committed in their CLAUDE.md
//    files; changing the format silently doubles the block (old marker
//    stays in place, new marker appended fresh).
// ⛔ NEVER include rule content that could be sensitive (raw command lines,
//    file paths with secrets, etc.) in the managed block — CLAUDE.md is
//    committed to git. Emit IDs + categories + short descriptions only.
// WHY: OpsContext-managed sections in CLAUDE.md are the highest-leverage
//    integration with Claude Code — CLAUDE.md is loaded at every session
//    start natively, so OpsContext's most-relevant intel lands in the
//    agent's context with zero MCP roundtrip.
// FIX: If the managed-block format needs to evolve, add a version line
//    inside the marker and have the rewriter accept both old and new
//    versions during a deprecation window.

import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { join, dirname, resolve } from "path";
import { homedir } from "os";
import type { KnowledgeSource } from "./config.js";

// ---------------------------------------------------------------------------
// A. Skill installation — copies bundled SKILL.md into Claude Code's skills dir
// ---------------------------------------------------------------------------

export type SkillInstallScope = "global" | "project";

export interface InstallSkillOpts {
  scope?: SkillInstallScope;
  cwd?: string;
  force?: boolean;
}

export interface InstallSkillResult {
  ok: boolean;
  installedTo: string;
  source: string;
  message: string;
  alreadyInstalled?: boolean;
}

/**
 * Locate the bundled skill directory regardless of how the package was
 * installed. Walks up from the running CLI to find the package root.
 */
export function locateBundledSkill(cliDistDir: string): string {
  // dist/cli.js → ../skills/opscontext/
  return resolve(cliDistDir, "..", "skills", "opscontext");
}

export function installSkill(
  bundledSkillDir: string,
  opts: InstallSkillOpts = {},
): InstallSkillResult {
  const scope = opts.scope ?? defaultScope(opts.cwd ?? process.cwd());
  const target =
    scope === "global"
      ? join(homedir(), ".claude", "skills", "opscontext")
      : join(opts.cwd ?? process.cwd(), ".claude", "skills", "opscontext");

  const sourceSkillFile = join(bundledSkillDir, "SKILL.md");
  const targetSkillFile = join(target, "SKILL.md");

  if (!existsSync(sourceSkillFile)) {
    return {
      ok: false,
      installedTo: target,
      source: bundledSkillDir,
      message: `Bundled skill not found at ${sourceSkillFile}. Reinstall @compr/opscontext-mcp.`,
    };
  }

  if (existsSync(targetSkillFile) && !opts.force) {
    return {
      ok: true,
      installedTo: target,
      source: bundledSkillDir,
      alreadyInstalled: true,
      message: `Skill already installed at ${target}. Pass --force to overwrite.`,
    };
  }

  mkdirSync(target, { recursive: true });
  writeFileSync(targetSkillFile, readFileSync(sourceSkillFile, "utf-8"));

  return {
    ok: true,
    installedTo: target,
    source: bundledSkillDir,
    message: `✅ Installed opscontext skill → ${targetSkillFile}`,
  };
}

function defaultScope(cwd: string): SkillInstallScope {
  // If the project has its own .claude/ dir, install there. Otherwise global.
  return existsSync(join(cwd, ".claude")) ? "project" : "global";
}

// ---------------------------------------------------------------------------
// B. CLAUDE.md auto-managed section
// ---------------------------------------------------------------------------

const BEGIN_MARKER =
  "<!-- BEGIN: managed by OpsContext (regenerated by `opscontext sync-claude-md`; manual edits to this block are overwritten) -->";
const END_MARKER = "<!-- END: managed by OpsContext -->";

export interface ManagedBlockInput {
  projectName: string;
  topLearnings: Array<{ id: string; category: string; rule: string; project?: string }>;
  policySummary: {
    secretPatternCount: number;
    secretPatternIds: string[];
    docCoverageCount: number;
    deployVerifyHostCount: number;
    bypassTokenCount: number;
  } | null;
  recentBlocks: Array<{ ts: string; check: string; reason: string }>;
  generatedAt: string;
}

/**
 * Build the managed-block content. Pure function — easy to test, never
 * touches the filesystem.
 *
 * The format is intentionally compact: Claude Code's CLAUDE.md is loaded
 * into every session's context, so each byte costs token budget. Aim for
 * <500 tokens (~2000 chars) of content between the markers.
 */
export function buildManagedBlock(input: ManagedBlockInput): string {
  const lines: string[] = [];
  lines.push(BEGIN_MARKER);
  lines.push(`## OpsContext snapshot for ${input.projectName}`);
  lines.push("");
  lines.push(`_Regenerated ${input.generatedAt}. Run \`opscontext sync-claude-md\` to refresh._`);
  lines.push("");

  // Top learnings — the recall hits the agent's context every session
  if (input.topLearnings.length > 0) {
    lines.push("### Top operational rules for this project");
    for (const l of input.topLearnings) {
      // Short ID + category prefix so the agent can cite it back; rule is the
      // user-facing memory. Limit rule to one line to keep token budget low.
      const rule = l.rule.replace(/\s+/g, " ").trim().slice(0, 180);
      lines.push(`- [\`${l.id}\` · ${l.category}] ${rule}`);
    }
    lines.push("");
  }

  // Active policy gates — what the pre-commit hook will block
  if (input.policySummary) {
    lines.push("### Active policy gates (`.contextengine/policy.json`)");
    const p = input.policySummary;
    const parts: string[] = [];
    if (p.secretPatternCount > 0) {
      parts.push(
        `${p.secretPatternCount} secret pattern(s): ${p.secretPatternIds.slice(0, 5).join(", ")}${p.secretPatternIds.length > 5 ? "…" : ""}`,
      );
    }
    if (p.docCoverageCount > 0) parts.push(`${p.docCoverageCount} doc-coverage rule(s)`);
    if (p.deployVerifyHostCount > 0) parts.push(`${p.deployVerifyHostCount} deploy-verify host(s)`);
    if (p.bypassTokenCount > 0) parts.push(`${p.bypassTokenCount} bypass token(s)`);
    if (parts.length === 0) parts.push("policy.json present but no active rules");
    for (const p2 of parts) lines.push(`- ${p2}`);
    lines.push("");
  } else {
    lines.push("### Policy");
    lines.push(
      "- No `.contextengine/policy.json` in this repo. Run `opscontext policy validate <file>` to author one.",
    );
    lines.push("");
  }

  // Recent compliance events — show the agent what was blocked
  if (input.recentBlocks.length > 0) {
    lines.push("### Recent hook blocks (last 3, from `~/.contextengine/audit.log`)");
    for (const b of input.recentBlocks) {
      const ts = b.ts.split("T")[0];
      lines.push(`- ${ts} — \`${b.check}\` blocked: ${b.reason}`);
    }
    lines.push("");
  }

  lines.push(END_MARKER);
  return lines.join("\n");
}

/**
 * Write the managed block into CLAUDE.md. Idempotent: if markers exist,
 * replace the content between them. Otherwise append at end.
 *
 * Returns the modified file content (for testing) AND writes it to disk.
 */
export interface SyncResult {
  ok: boolean;
  mode: "replaced-existing-block" | "appended-new-block" | "created-new-file";
  filePath: string;
  bytesWritten: number;
}

export function syncClaudeMd(filePath: string, blockContent: string): SyncResult {
  let mode: SyncResult["mode"];
  let nextContent: string;

  if (!existsSync(filePath)) {
    mode = "created-new-file";
    nextContent = `# CLAUDE.md\n\n${blockContent}\n`;
  } else {
    const current = readFileSync(filePath, "utf-8");
    const beginIdx = current.indexOf(BEGIN_MARKER);
    const endIdx = current.indexOf(END_MARKER);

    if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
      // Replace the block + its trailing newline if present
      const afterEnd = endIdx + END_MARKER.length;
      const trailingNewline = current[afterEnd] === "\n" ? 1 : 0;
      nextContent =
        current.slice(0, beginIdx) +
        blockContent +
        current.slice(afterEnd + trailingNewline) +
        // ensure we don't end up with stray blanks at boundary
        (current[beginIdx - 1] === "\n" ? "" : "\n");
      mode = "replaced-existing-block";
    } else {
      // Append at end, with a leading newline if file doesn't end in one
      const sep = current.endsWith("\n") ? "" : "\n";
      nextContent = current + sep + "\n" + blockContent + "\n";
      mode = "appended-new-block";
    }
  }

  // Always ensure the file ends with a single newline (POSIX convention) so
  // a repeat sync with the same input is a true no-op.
  if (!nextContent.endsWith("\n")) nextContent += "\n";

  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, nextContent);
  return {
    ok: true,
    mode,
    filePath,
    bytesWritten: Buffer.byteLength(nextContent),
  };
}

// Exported for tests
export const _markers = { BEGIN_MARKER, END_MARKER };

// ---------------------------------------------------------------------------
// C. Claude Code auto-memory discovery
// ---------------------------------------------------------------------------

/**
 * Walk Claude Code's per-project auto-memory directories and surface every
 * .md file as a knowledge source. The structure is:
 *   ~/.claude/projects/<project-slug>/memory/MEMORY.md
 *   ~/.claude/projects/<project-slug>/memory/feedback_*.md
 *   ~/.claude/projects/<project-slug>/memory/project_*.md
 *   ... etc
 *
 * The <project-slug> is Claude Code's URL-safe encoding of an absolute path
 * (slashes become hyphens, leading hyphen). We display the decoded path for
 * readability in source names.
 *
 * Read-only: this function never modifies anything under ~/.claude/.
 */
export function discoverClaudeMemory(opts: { home?: string } = {}): KnowledgeSource[] {
  const home = opts.home ?? homedir();
  const root = join(home, ".claude", "projects");
  if (!existsSync(root)) return [];

  const sources: KnowledgeSource[] = [];

  let entries: string[];
  try {
    entries = readdirSync(root);
  } catch {
    return [];
  }

  for (const slug of entries) {
    const memDir = join(root, slug, "memory");
    if (!existsSync(memDir)) continue;
    let files: string[];
    try {
      files = readdirSync(memDir);
    } catch {
      continue;
    }
    const displayPath = decodeClaudeProjectSlug(slug);
    for (const f of files) {
      if (!f.endsWith(".md")) continue;
      const filePath = join(memDir, f);
      sources.push({
        name: `Claude memory — ${displayPath} — ${f}`,
        path: filePath,
        type: "markdown",
      });
    }
  }

  return sources;
}

/**
 * Decode Claude Code's project slug back into a readable path.
 * Encoding: leading hyphen, slashes → hyphens. e.g.
 *   -Users-yan-Projects-INVOK-fr → /Users/yan/Projects/INVOK-fr
 *
 * Not perfectly reversible (a dir literally named "foo-bar" looks the same
 * as a path /foo/bar) but good enough for the display label.
 */
export function decodeClaudeProjectSlug(slug: string): string {
  if (!slug.startsWith("-")) return slug;
  // Replace the leading hyphen with a slash, leave the rest as-is for
  // the display label.
  return "/" + slug.slice(1);
}
